### ISSUE TITLE
Any reason version isn't exposed in mjs?

### ISSUE THREAD

**Issue by mickeyschwab** [mongoose-os-libs/shadow#3]
Just curious why mjs doesn't allow passthrough of the shadow version as AWS shadows, Azure Twins, and GCP Configurations all support version and therefore it feels like it's part of a common api. If there's a better way to handle invalidating received states that conflict with reported state, please let me know.

**Comment by cpq** [comment]
Passing version is the right way, feel free to patch JS code and send a PR

**Comment by mickeyschwab** [comment]
Will do, thanks.
